<a href="https://colab.research.google.com/github/rachithvs/rachith-vasuman-s/blob/main/Copy_of_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1) Create a row and column vector using input method and manually

In [9]:
import numpy as np
row_input = input("Enter space-separated values for the row vector: ")
row_values = [float(x) for x in row_input.split()]
row_vect = np.array(row_values)

print("Row vector:")
print(row_vect)

Enter space-separated values for the row vector: 1 2 3 4 5
Row vector:
[1. 2. 3. 4. 5.]


In [11]:
col_input = input("Enter space-separated values for the column vector: ")
col_values = [float(x) for x in col_input.split()]
col_vect = np.array(col_values).reshape(-1, 1)

print("Column vector:")
print(col_vect)

Enter space-separated values for the column vector: 1 2 3 4 5
Column vector:
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [ ]:
#2) Create a matrix (5 × 5) using the input method as well as manually and save it as “a”.

In [12]:
input_matrix = []
print("Enter values for the 5x5 matrix:")

for _ in range(5):
    row_input = input(f"Enter 5 space-separated values for row {_ + 1}: ")
    row_values = [float(x) for x in row_input.split()]
    input_matrix.append(row_values)

a = np.array(input_matrix)

print("Matrix 'a' created using user input:")
print(a)

Enter values for the 5x5 matrix:
Enter 5 space-separated values for row 1: 1 2 3 4 5 
Enter 5 space-separated values for row 2: 6 7 8 9 10
Enter 5 space-separated values for row 3: 11 12 13 14 15
Enter 5 space-separated values for row 4: 16 17 18 19 20 
Enter 5 space-separated values for row 5: 21 22 23 24 25
Matrix 'a' created using user input:
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [ ]:
#3) Get 3rd row out of the matrix.

In [13]:
a[2]

array([11., 12., 13., 14., 15.])

In [ ]:
#4) Get 4th column out of the matrix

In [14]:
print(a[0][3])
print(a[1][3])
print(a[2][3])
print(a[3][3])
print(a[4][3])

4.0
9.0
14.0
19.0
24.0


In [ ]:
#5) Sort matrix row wise and column wise

In [15]:
a.sort()
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [ ]:
#6) Apply for loop in matrix, if element is greater than 2, multiply element by 10 say it as “b”.

In [16]:
b = np.copy(a)  # Create a copy of the matrix

for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        if b[i, j] > 2:
            b[i, j] *= 10

print("Matrix 'b' after applying for loop:")
print(b)

Matrix 'b' after applying for loop:
[[  1.   2.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [160. 170. 180. 190. 200.]
 [210. 220. 230. 240. 250.]]


In [17]:
#7) Add matrix a and b.

In [18]:
sum_matrix = a + b

print("Sum of matrices 'a' and 'b':")
print(sum_matrix)

Sum of matrices 'a' and 'b':
[[  2.   4.  33.  44.  55.]
 [ 66.  77.  88.  99. 110.]
 [121. 132. 143. 154. 165.]
 [176. 187. 198. 209. 220.]
 [231. 242. 253. 264. 275.]]


In [19]:
#8) Subtract matrix b from a

In [20]:
diff_matrix = a - b

print("Subtraction of matrix 'b' from 'a':")
print(diff_matrix)

Subtraction of matrix 'b' from 'a':
[[   0.    0.  -27.  -36.  -45.]
 [ -54.  -63.  -72.  -81.  -90.]
 [ -99. -108. -117. -126. -135.]
 [-144. -153. -162. -171. -180.]
 [-189. -198. -207. -216. -225.]]


In [21]:
#9) Multiply matrix a by b element wise and matrix multiplication

In [22]:
elementwise_product = a * b

print("Element-wise multiplication of matrices 'a' and 'b':")
print(elementwise_product)

Element-wise multiplication of matrices 'a' and 'b':
[[1.00e+00 4.00e+00 9.00e+01 1.60e+02 2.50e+02]
 [3.60e+02 4.90e+02 6.40e+02 8.10e+02 1.00e+03]
 [1.21e+03 1.44e+03 1.69e+03 1.96e+03 2.25e+03]
 [2.56e+03 2.89e+03 3.24e+03 3.61e+03 4.00e+03]
 [4.41e+03 4.84e+03 5.29e+03 5.76e+03 6.25e+03]]


In [23]:
# Matrix multiplication (Dot product)
matrix_product = np.dot(a, b)

print("Matrix multiplication of matrices 'a' and 'b':")
print(matrix_product)

Matrix multiplication of matrices 'a' and 'b':
[[ 2141.  2282.  2450.  2600.  2750.]
 [ 4846.  5192.  5700.  6100.  6500.]
 [ 7551.  8102.  8950.  9600. 10250.]
 [10256. 11012. 12200. 13100. 14000.]
 [12961. 13922. 15450. 16600. 17750.]]


In [24]:
#10) Divide each element of matrix a and b by 18.

In [25]:
a_divided = a / 18
b_divided = b / 18

print("Matrix 'a' after element-wise division:")
print(a_divided)

print("Matrix 'b' after element-wise division:")
print(b_divided)

Matrix 'a' after element-wise division:
[[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.33333333 0.38888889 0.44444444 0.5        0.55555556]
 [0.61111111 0.66666667 0.72222222 0.77777778 0.83333333]
 [0.88888889 0.94444444 1.         1.05555556 1.11111111]
 [1.16666667 1.22222222 1.27777778 1.33333333 1.38888889]]
Matrix 'b' after element-wise division:
[[ 0.05555556  0.11111111  1.66666667  2.22222222  2.77777778]
 [ 3.33333333  3.88888889  4.44444444  5.          5.55555556]
 [ 6.11111111  6.66666667  7.22222222  7.77777778  8.33333333]
 [ 8.88888889  9.44444444 10.         10.55555556 11.11111111]
 [11.66666667 12.22222222 12.77777778 13.33333333 13.88888889]]


In [27]:
#11) find the inverse, rank, condition number, singular value decomposition and the norm of matrices a and b.

In [28]:
#Inverses of matrices
a_inv = np.linalg.inv(a)
b_inv = np.linalg.inv(b)
print("Inverse of matrix 'a':")
print(a_inv)
print("Inverse of matrix 'b':")
print(b_inv)


LinAlgError: ignored

In [29]:
# Rank of matrices
rank_a = np.linalg.matrix_rank(a)
rank_b = np.linalg.matrix_rank(b)
print("Rank of matrix 'a':", rank_a)
print("Rank of matrix 'b':", rank_b)


Rank of matrix 'a': 2
Rank of matrix 'b': 3


In [30]:
# Condition number of matrices
cond_a = np.linalg.cond(a)
cond_b = np.linalg.cond(b)
print("Condition number of matrix 'a':", cond_a)
print("Condition number of matrix 'b':", cond_b)

Condition number of matrix 'a': 3.5675570478720614e+17
Condition number of matrix 'b': 1.1160764850096235e+17


In [31]:
# Singular Value Decomposition (SVD)
u_a, s_a, vh_a = np.linalg.svd(a)
u_b, s_b, vh_b = np.linalg.svd(b)
print("Singular Value Decomposition of matrix 'a':")
print("U:")
print(u_a)
print("Singular values:")
print(s_a)
print("V^H:")
print(vh_a)
print("Singular Value Decomposition of matrix 'b':")
print("U:")
print(u_b)
print("Singular values:")
print(s_b)
print("V^H:")
print(vh_b)

Singular Value Decomposition of matrix 'a':
U:
[[-0.09359323 -0.76892152  0.61130515  0.0196316  -0.16099879]
 [-0.24363203 -0.49055421 -0.5142169  -0.45682855  0.4763283 ]
 [-0.39367083 -0.2121869  -0.3594458   0.81870773 -0.02272392]
 [-0.54370962  0.06618041 -0.18367831 -0.34545623 -0.73954194]
 [-0.69374842  0.34454772  0.44603585 -0.03605456  0.44693633]]
Singular values:
[7.42540539e+01 3.36681954e+00 2.98266488e-15 1.53916447e-15
 2.08136977e-16]
V^H:
[[-0.39262281 -0.41913118 -0.44563955 -0.47214793 -0.4986563 ]
 [ 0.667718    0.35260325  0.0374885  -0.27762625 -0.592741  ]
 [ 0.5359956  -0.50603463 -0.52349916  0.42111979  0.0724184 ]
 [-0.33541664  0.36000724 -0.21070021  0.68304527 -0.49693566]
 [ 0.01429645 -0.56064583  0.69394096  0.23686977 -0.38446135]]
Singular Value Decomposition of matrix 'b':
U:
[[-7.88349250e-02 -8.83486145e-01  4.61776230e-01  8.78631692e-16
  -4.02440250e-17]
 [-2.43962900e-01 -3.53507967e-01 -7.17993190e-01  2.06990739e-01
   5.07104362e-01]
 [-3

In [32]:
# Norms of matrices
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
print("Norm of matrix 'a':", norm_a)
print("Norm of matrix 'b':", norm_b)

Norm of matrix 'a': 74.33034373659252
Norm of matrix 'b': 742.9703897195366


In [33]:
#12) find the norm, inner product and outer product of column vector.

In [34]:
#norm of column vector
norm_v = np.linalg.norm(v)
print("Norm of the column vector 'v':", norm_v)

NameError: ignored

In [37]:
#inner product of column vector
inner_product = np.dot(v.T,v)
print("Inner product of the column vector 'v' with itself:")
print(inner_product)

NameError: ignored

In [36]:
#outer product of column vector
outer_product = np.outer(v, v.T)
print("Outer product of the column vector 'v' with itself:")
print(outer_product)

NameError: ignored