<a href="https://colab.research.google.com/github/rachithvs/rachith-vasuman-s/blob/main/rachith%20vasuman%20s_231030042_assingment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1) Create a row and column vector using input method and manually

In [2]:
import numpy as np
row_input = input("Enter space-separated values for the row vector: ")
row_values = [float(x) for x in row_input.split()]
row_vect = np.array(row_values)

print("Row vector:")
print(row_vect)

Enter space-separated values for the row vector: 1 2 3 4 5
Row vector:
[1. 2. 3. 4. 5.]


In [3]:
col_input = input("Enter space-separated values for the column vector: ")
col_values = [float(x) for x in col_input.split()]
col_vect = np.array(col_values).reshape(-1, 1)

print("Column vector:")
print(col_vect)

Enter space-separated values for the column vector: 1 2 3 4 5
Column vector:
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [ ]:
#2) Create a matrix (5 × 5) using the input method as well as manually and save it as “a”.

In [4]:
import numpy as np

input_matrix = []
print("Enter values for the 5x5 matrix:")

for _ in range(5):
    row_input = input(f"Enter 5 space-separated values for row {_ + 1}: ")
    row_values = [float(x) for x in row_input.split()]
    input_matrix.append(row_values)

a = np.array(input_matrix)

print("Matrix 'a' created using user input:")
print(a)

Enter values for the 5x5 matrix:
Enter 5 space-separated values for row 1: 8 7 6 3 2 
Enter 5 space-separated values for row 2: 9 5 1 0 5
Enter 5 space-separated values for row 3: 2 6 4 7 1
Enter 5 space-separated values for row 4: 0 8 3 6 1
Enter 5 space-separated values for row 5: 5 7 2 9 2
Matrix 'a' created using user input:
[[8. 7. 6. 3. 2.]
 [9. 5. 1. 0. 5.]
 [2. 6. 4. 7. 1.]
 [0. 8. 3. 6. 1.]
 [5. 7. 2. 9. 2.]]


In [ ]:
8#3) Get 3rd row out of the matrix.

In [5]:
a[2]

array([2., 6., 4., 7., 1.])

In [ ]:
#4) Get 4th column out of the matrix

In [6]:
print(a[0][3])
print(a[1][3])
print(a[2][3])
print(a[3][3])
print(a[4][3])

3.0
0.0
7.0
6.0
9.0


In [ ]:
#5) Sort matrix row wise and column wise

In [7]:
a.sort()
print(a)

[[2. 3. 6. 7. 8.]
 [0. 1. 5. 5. 9.]
 [1. 2. 4. 6. 7.]
 [0. 1. 3. 6. 8.]
 [2. 2. 5. 7. 9.]]


In [ ]:
#6) Apply for loop in matrix, if element is greater than 2, multiply element by 10 say it as “b”.

In [8]:
b = np.copy(a)  # Create a copy of the matrix

for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        if b[i, j] > 2:
            b[i, j] *= 10

print("Matrix 'b' after applying for loop:")
print(b)

Matrix 'b' after applying for loop:
[[ 2. 30. 60. 70. 80.]
 [ 0.  1. 50. 50. 90.]
 [ 1.  2. 40. 60. 70.]
 [ 0.  1. 30. 60. 80.]
 [ 2.  2. 50. 70. 90.]]


In [ ]:
#7) Add matrix a and b.

In [9]:
sum_matrix = a + b

print("Sum of matrices 'a' and 'b':")
print(sum_matrix)

Sum of matrices 'a' and 'b':
[[ 4. 33. 66. 77. 88.]
 [ 0.  2. 55. 55. 99.]
 [ 2.  4. 44. 66. 77.]
 [ 0.  2. 33. 66. 88.]
 [ 4.  4. 55. 77. 99.]]


In [ ]:
#8) Subtract matrix b from a

In [10]:
diff_matrix = a - b

print("Subtraction of matrix 'b' from 'a':")
print(diff_matrix)

Subtraction of matrix 'b' from 'a':
[[  0. -27. -54. -63. -72.]
 [  0.   0. -45. -45. -81.]
 [  0.   0. -36. -54. -63.]
 [  0.   0. -27. -54. -72.]
 [  0.   0. -45. -63. -81.]]


In [ ]:
#9) Multiply matrix a by b element wise and matrix multiplication

In [11]:
elementwise_product = a * b

print("Element-wise multiplication of matrices 'a' and 'b':")
print(elementwise_product)

Element-wise multiplication of matrices 'a' and 'b':
[[  4.  90. 360. 490. 640.]
 [  0.   1. 250. 250. 810.]
 [  1.   4. 160. 360. 490.]
 [  0.   1.  90. 360. 640.]
 [  4.   4. 250. 490. 810.]]


In [12]:
# Matrix multiplication (Dot product)
matrix_product = np.dot(a, b)

print("Matrix multiplication of matrices 'a' and 'b':")
print(matrix_product)

Matrix multiplication of matrices 'a' and 'b':
[[  26.   98. 1120. 1630. 2130.]
 [  23.   34.  850. 1280. 1650.]
 [  20.   60.  850. 1260. 1650.]
 [  19.   29.  750. 1150. 1500.]
 [  27.   97. 1080. 1590. 2060.]]


In [ ]:
#10) Divide each element of matrix a and b by 18.

In [13]:
a_divided = a / 18
b_divided = b / 18

print("Matrix 'a' after element-wise division:")
print(a_divided)

print("Matrix 'b' after element-wise division:")
print(b_divided)

Matrix 'a' after element-wise division:
[[0.11111111 0.16666667 0.33333333 0.38888889 0.44444444]
 [0.         0.05555556 0.27777778 0.27777778 0.5       ]
 [0.05555556 0.11111111 0.22222222 0.33333333 0.38888889]
 [0.         0.05555556 0.16666667 0.33333333 0.44444444]
 [0.11111111 0.11111111 0.27777778 0.38888889 0.5       ]]
Matrix 'b' after element-wise division:
[[0.11111111 1.66666667 3.33333333 3.88888889 4.44444444]
 [0.         0.05555556 2.77777778 2.77777778 5.        ]
 [0.05555556 0.11111111 2.22222222 3.33333333 3.88888889]
 [0.         0.05555556 1.66666667 3.33333333 4.44444444]
 [0.11111111 0.11111111 2.77777778 3.88888889 5.        ]]


In [ ]:
#11) find the inverse, rank, condition number, singular value decomposition and the norm of matrices a and b.

In [26]:
  import numpy as np

# Assuming 'a' and 'b' are the matrices  we have created in pervious question
# Inverse of matrix 'a'
try:
    inverse_a = np.linalg.inv(a)
    print("Inverse of matrix 'a':")
    print(inverse_a)
except np.linalg.LinAlgError:
    print("Matrix 'a' is not invertible.")

# Inverse of matrix 'b'
try:
    inverse_b = np.linalg.inv(b)
    print("Inverse of matrix 'b':")
    print(inverse_b)
except np.linalg.LinAlgError:
    print("Matrix 'b' is not invertible.")

# Rank of matrix 'a'
rank_a = np.linalg.matrix_rank(a)
print("Rank of matrix 'a':", rank_a)

# Rank of matrix 'b'
rank_b = np.linalg.matrix_rank(b)
print("Rank of matrix 'b':", rank_b)

# Condition number of matrix 'a'
condition_number_a = np.linalg.cond(a)
print("Condition number of matrix 'a':", condition_number_a)

# Condition number of matrix 'b'
condition_number_b = np.linalg.cond(b)
print("Condition number of matrix 'b':", condition_number_b)

# Singular value decomposition (SVD) of matrix 'a'
U_a, S_a, Vt_a = np.linalg.svd(a)
print("Singular Value Decomposition of matrix 'a':")
print("U_a:", U_a)
print("S_a:", S_a)
print("Vt_a:", Vt_a)

# Singular value decomposition (SVD) of matrix 'b'
U_b, S_b, Vt_b = np.linalg.svd(b)
print("Singular Value Decomposition of matrix 'b':")
print("U_b:", U_b)
print("S_b:", S_b)
print("Vt_b:", Vt_b)

# Norm of matrix 'a'
norm_a = np.linalg.norm(a)
print("Norm of matrix 'a':", norm_a)

# Norm of matrix 'b'
norm_b = np.linalg.norm(b)
print("Norm of matrix 'b':", norm_b)

Inverse of matrix 'a':
[[-1.00000000e+00  4.44089210e-16  1.00000000e+00 -1.00000000e+00
   1.00000000e+00]
 [-1.06666667e+01  2.33333333e+00  1.93333333e+01 -1.00000000e+01
   1.00000000e+00]
 [ 6.00000000e+00 -1.00000000e+00 -1.00000000e+01  5.00000000e+00
  -1.00000000e+00]
 [ 6.33333333e+00 -1.66666667e+00 -1.06666667e+01  6.00000000e+00
  -1.00000000e+00]
 [-5.66666667e+00  1.33333333e+00  9.33333333e+00 -5.00000000e+00
   1.00000000e+00]]
Inverse of matrix 'b':
[[ 0.00348432 -0.2195122  -0.81881533 -0.05923345  0.90592334]
 [ 0.03716609 -0.00813008 -0.06736353  0.03484321 -0.00348432]
 [-0.00209059  0.03170732  0.0912892  -0.06445993 -0.04355401]
 [-0.00220674 -0.02764228  0.08524971  0.00418118 -0.04041812]
 [ 0.00197445  0.00894309 -0.09732869  0.03310105  0.0466899 ]]
Rank of matrix 'a': 5
Rank of matrix 'b': 5
Condition number of matrix 'a': 852.5172125019204
Condition number of matrix 'b': 317.3385418361312
Singular Value Decomposition of matrix 'a':
U_a: [[-0.48968469  0.62

In [15]:
# Rank of matrices
rank_a = np.linalg.matrix_rank(a)
rank_b = np.linalg.matrix_rank(b)
print("Rank of matrix 'a':", rank_a)
print("Rank of matrix 'b':", rank_b)


Rank of matrix 'a': 5
Rank of matrix 'b': 5


In [16]:
# Condition number of matrices
cond_a = np.linalg.cond(a)
cond_b = np.linalg.cond(b)
print("Condition number of matrix 'a':", cond_a)
print("Condition number of matrix 'b':", cond_b)

Condition number of matrix 'a': 852.5172125019204
Condition number of matrix 'b': 317.3385418361312


In [17]:
# Singular Value Decomposition (SVD)
u_a, s_a, vh_a = np.linalg.svd(a)
u_b, s_b, vh_b = np.linalg.svd(b)
print("Singular Value Decomposition of matrix 'a':")
print("U:")
print(u_a)
print("Singular values:")
print(s_a)
print("V^H:")
print(vh_a)
print("Singular Value Decomposition of matrix 'b':")
print("U:")
print(u_b)
print("Singular values:")
print(s_b)
print("V^H:")
print(vh_b)

Singular Value Decomposition of matrix 'a':
U:
[[-0.48968469  0.6217437  -0.22808617 -0.34503195 -0.45008146]
 [-0.44002943 -0.55082693 -0.70143832 -0.03363068  0.09908106]
 [-0.39957391  0.14586297  0.26443501 -0.36724703  0.78375278]
 [-0.40177994 -0.5096386   0.60410116 -0.20985866 -0.4121438 ]
 [-0.49547611  0.17034366  0.14524768  0.83720421  0.05898037]]
Singular values:
[25.70967289  2.91141864  1.71269268  0.77597407  0.03015737]
V^H:
[[-0.09217914 -0.15951053 -0.40526658 -0.54082352 -0.71367241]
 [ 0.59422498  0.49363524  0.30314498  0.20877214 -0.51743429]
 [ 0.05766243  0.02205282 -0.74702643  0.65636761 -0.08556745]
 [ 0.79525531 -0.43644605 -0.19444995 -0.23915964  0.28648861]
 [ 0.05141705  0.73478511 -0.38471139 -0.41941428  0.36542569]]
Singular Value Decomposition of matrix 'b':
U:
[[-0.48597816  0.85049027  0.00836236 -0.20100891 -0.00412576]
 [-0.44721111 -0.28960184  0.82036439 -0.1135571   0.17389666]
 [-0.39571096 -0.09188364 -0.31436625  0.54119534  0.6657715 ]
 

In [18]:
# Norms of matrices
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
print("Norm of matrix 'a':", norm_a)
print("Norm of matrix 'b':", norm_b)

Norm of matrix 'a': 25.942243542145693
Norm of matrix 'b': 255.77138229285933


In [ ]:
#12) find the norm, inner product and outer product of column vector.

In [23]:
import numpy as np

# Create a column vector manually
column_vector = np.array([[1], [2], [3], [4], [5]])

# Calculate the norm of the column vector
norm = np.linalg.norm(column_vector)
print("Norm of the column vector:", norm)

# Create another column vector for inner product
inner_product_vector = np.array([[2], [4], [6], [8], [10]])

# Calculate the inner product of the two column vectors
inner_product = np.inner(column_vector.flatten(), inner_product_vector.flatten())
print("Inner product of the column vectors:", inner_product)

# Calculate the outer product of the two column vectors
outer_product = np.outer(column_vector, inner_product_vector.T)
print("Outer product of the column vectors:")
print(outer_product)

Norm of the column vector: 7.416198487095663
Inner product of the column vectors: 110
Outer product of the column vectors:
[[ 2  4  6  8 10]
 [ 4  8 12 16 20]
 [ 6 12 18 24 30]
 [ 8 16 24 32 40]
 [10 20 30 40 50]]


In [1]:
#13) Write a function called derivative which takes input parameters f(x), a, method (forward,backward and central) and h(step size) (with default values method=‘central’ and h = 0.01) and returns the
      #corresponding difference formula for derivative of function at a with step size h and then test your function on e x and cos x at x = 0.5.

In [24]:
import math

def derivative(f, a, method='central', h=0.01):
    # Implementation of the numerical derivative using different methods.
    # Returns the approximate derivative of function f at point a.
    if method == 'forward':
        return (f(a + h) - f(a)) / h# using first derivative formula
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    elif method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    else:
        raise ValueError("Invalid method, supported methods are 'forward', 'backward', and 'central'.")

def ex(x):#an maths function for determining exponent
    return math.exp(x)

def cos(x):# an maths function for determining cosine
    return math.cos(x)


x = 0.5 # value of x is intialized

derivative_ex_forward = derivative(ex, x, method='forward')# for x =0.5 forward derivative is carried out in ex()
derivative_ex_backward = derivative(ex, x, method='backward')#for x =0.5 backward derivative is carried out in ex()
derivative_ex_central = derivative(ex, x, method='central')#for x =0.5 central derivative is carried out in ex()

derivative_cos_forward = derivative(cos, x, method='forward')#for x =0.5 forward derivative is carried out in cos()
derivative_cos_backward = derivative(cos, x, method='backward')#for x =0.5 backward derivative is carried out in cos()
derivative_cos_central = derivative(cos, x, method='central')#for x =0.5 backward derivative is carried out in cos()

print("Testing on ex(x) at x =",x)
print("Forward difference:", derivative_ex_forward)
print("Backward difference:", derivative_ex_backward)
print("Central difference:", derivative_ex_central)

print("\nTesting on cos(x) at x =",x)
print("Forward difference:", derivative_cos_forward)
print("Backward difference:", derivative_cos_backward)
print("Central difference:", derivative_cos_central)


Testing on ex(x) at x = 0.5
Forward difference: 1.6569924245758205
Backward difference: 1.6405050744749294
Central difference: 1.648748749525375

Testing on cos(x) at x = 0.5
Forward difference: -0.483805424462147
Backward difference: -0.4750296719748692
Central difference: -0.4794175482185081


In [27]:
# 14) Download the Automatic Weather Station AWS Data. Read the .csv file using pandas library as a DataFrame

In [32]:
import pandas as pd

# Provide the path to your CSV file
csv_file_path = "/content/surface_data.csv"

# Read the CSV file into a DataFrame
df = pd.read_csv(csv_file_path)

# Display the first few rows of the DataFrame
print(df.head())

      obstime     tempr        ap      ws       wd       rh
0  1985-02-26  -10.0000  983.0250  16.125   11.750   64.875
1  1985-02-27  -12.6250  981.5750   5.875   29.250   58.625
2  1985-02-28  -17.1875  983.7750   3.000   99.000   55.125
3  1985-03-01 -507.6250  986.3375  19.125 -493.625 -999.000
4  1985-03-02 -257.3125  497.7500  33.875 -243.000 -224.125
