<a href="https://colab.research.google.com/github/rachithvs/rachith-vasuman-s/blob/main/Shivesh_kumar_verma_231030056_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Using input method to create a row vector
row_vector_entry = input("Enter values for row vector (in space separated): ")
row_vector = np.array([float(val) for val in row_vector_entry.split()])
# split () method splits a string into a list


# Using input method to create a column vector
column_vector_entry = input("Enter values for column vector (in space separated): ")
c_vector = np.array([float(val) for val in column_vector_entry.split()]).reshape(-1, 1)
#The reshape() is used to give a new shape to an array without changing its data. It enables us to change the dimensions of the array elements.


print("Row Vector:")
print(row_vector)

print("Column Vector:")
print(c_vector)


Enter values for row vector (in space separated): 1 2 6 5 8 7
Enter values for column vector (in space separated): 2 5 6 8 6
Row Vector:
[1. 2. 6. 5. 8. 7.]
Column Vector:
[[2.]
 [5.]
 [6.]
 [8.]
 [6.]]


In [ ]:
import numpy as np

# Creating a row vector as fixed data is entered
row_vector = np.array([55, 25, 25, 44])

# Creating a column vector as fixed data is entered
c_vector = np.array([[45], [96], [74], [88]])

print("Row Vector:")
print(row_vector)

print("Column Vector:")
print(c_vector)


Row Vector:
[55 25 25 44]
Column Vector:
[[45]
 [96]
 [74]
 [88]]


Question 2

In [ ]:
import numpy as np

# Using input method to create a matrix
matrix_input = []
for i in range(5):
    row_input = input(f"Enter values for row {i+1} (space-separated): ")
    row = [float(val) for val in row_input.split()]
    matrix_input.append(row)

a = np.array(matrix_input)

print("Matrix 'a':")
print(a)


Enter values for row 1 (space-separated): 1 5 9 6 4
Enter values for row 2 (space-separated): 4 6 3 5 9 
Enter values for row 3 (space-separated):  56 56 42 89 99
Enter values for row 4 (space-separated): 1 56 4 89 69
Enter values for row 5 (space-separated): 2 69 56 25 14
Matrix 'a':
[[ 1.  5.  9.  6.  4.]
 [ 4.  6.  3.  5.  9.]
 [56. 56. 42. 89. 99.]
 [ 1. 56.  4. 89. 69.]
 [ 2. 69. 56. 25. 14.]]


Question 3

In [ ]:
# Extracting the 3rd row
third_row = a[2, :]

print("3rd Row:")
print(third_row)

3rd Row:
[56. 56. 42. 89. 99.]


Question 4

In [ ]:
# Extracting the 4th column
fourth_column = a[:, 3]

print("4th Column:")
print(fourth_column)

4th Column:
[ 6.  5. 89. 89. 25.]


Question 6

In [ ]:
a = [
    [16, 25,36, 49, 64],
    [81, 9, 4, 1, 0],
    [14, 35, 56, 63, 12],
    [6, 12, 18, 24, 18],
    [25, 32, 55, 244, 121]
]


# Sort matrix row-wise
for row in a:
    row.sort()

# Transpose the matrix for column-wise sorting
transposed_a = [[a[j][i] for j in range(len(a))] for i in range(len(a[0]))]

# Sort transposed matrix (column-wise sorting)
for row in transposed_a:
    row.sort()

# Transpose the sorted matrix back to get the original orientation
sorted_a = [[transposed_a[j][i] for j in range(len(transposed_a))] for i in range(len(transposed_a[0]))]

# Print sorted matrix row-wise
print("Sorted Matrix Row-wise:")
for row in sorted_a:
    print(row)

# Transpose the sorted matrix again for printing sorted matrix column-wise
sorted_column_a = [[sorted_a[j][i] for j in range(len(sorted_a))] for i in range(len(sorted_a[0]))]

# Print sorted matrix column-wise
print("Sorted Matrix Column-wise:")
for row in sorted_column_a:
    print(row)

Sorted Matrix Row-wise:
[0, 1, 4, 9, 24]
[6, 12, 18, 18, 63]
[12, 14, 35, 49, 64]
[16, 25, 36, 56, 81]
[25, 32, 55, 121, 244]
Sorted Matrix Column-wise:
[0, 6, 12, 16, 25]
[1, 12, 14, 25, 32]
[4, 18, 35, 36, 55]
[9, 18, 49, 56, 121]
[24, 63, 64, 81, 244]



Qujestion 6

In [ ]:
#  Assuming 'a' is the matrix we have created in previous question

# Initialize an empty matrix 'b'
b = []

# Loop through each row in matrix 'a'
for row in a:
    new_row = []

    # Loop through each element in the row
    for element in row:
        # Check if the element is greater than 2
        if element > 2:
            new_element = element * 10
        else:
            new_element = element

        new_row.append(new_element)

    b.append(new_row)

# Print matrix 'b'
print("Matrix 'b' (after multiplying elements > 2 by 10):")
for row in b:
    print(row)

Matrix 'b' (after multiplying elements > 2 by 10):
[160, 250, 360, 490, 640]
[0, 1, 40, 90, 810]
[120, 140, 350, 560, 630]
[60, 120, 180, 180, 240]
[250, 320, 550, 1210, 2440]


Question 7

In [ ]:

# Initialize an empty matrix 'c'and auusming 'a' and 'b'to be earlier matrix
c = []

# Loop through each row in matrices 'a' and 'b'
for row_a, row_b in zip(a, b):
    new_row = []

    # Loop through each element in the rows of 'a' and 'b'
    for element_a, element_b in zip(row_a, row_b):
        # Add corresponding elements from 'a' and 'b'
        new_element = element_a + element_b
        new_row.append(new_element)

    c.append(new_row)

# Print matrix 'c'
print("Matrix 'c' (result of a + b):")
for row in c:
    print(row)

Matrix 'c' (result of a + b):
[176, 275, 396, 539, 704]
[0, 2, 44, 99, 891]
[132, 154, 385, 616, 693]
[66, 132, 198, 198, 264]
[275, 352, 605, 1331, 2684]


Question 8

In [ ]:
# Initialize an empty matrix 'd'
d = []

# Loop through each row in matrices 'a' and 'b'
for row_a, row_b in zip(a, b):
    new_row = []

    # Loop through each element in the rows of 'a' and 'b'
    for element_a, element_b in zip(row_a, row_b):
        # Subtract corresponding elements of 'b' from 'a'
        new_element = element_a - element_b
        new_row.append(new_element)

    d.append(new_row)

# Print matrix 'd'
print("Matrix 'd' (result of a - b):")
for row in d:
    print(row)

Matrix 'd' (result of a - b):
[-144, -225, -324, -441, -576]
[0, 0, -36, -81, -729]
[-108, -126, -315, -504, -567]
[-54, -108, -162, -162, -216]
[-225, -288, -495, -1089, -2196]


Question 9

In [ ]:
# Assuming 'a' and 'b' are the matrices we have created in earlier question

# Element-wise multiplication of matrices 'a' and 'b'

import numpy as np
element_wise_product = np.multiply(a, b)

# Matrix multiplication of matrices 'a' and 'b'
matrix_product = np.dot(a, b)

# Print element-wise product
print("Element-wise Product of a and b:")
print(element_wise_product)

# Print matrix product
print("Matrix Product of a and b:")
print(matrix_product)

Element-wise Product of a and b:
[[  2560   6250  12960  24010  40960]
 [     0      1    160    810  65610]
 [  1440   1960  12250  31360  39690]
 [   360   1440   3240   3240   5760]
 [  6250  10240  30250 146410 595360]]
Matrix Product of a and b:
[[ 25820  35425  63380 116510 221090]
 [ 21270  27561  47610 101960 203130]
 [ 25230  34794  61860 113050 208230]
 [ 10200  13872  25380  46380  87780]
 [ 78860 106582 185510 362950 700970]]


Question 10

In [ ]:
# Assuming 'a' and 'b' are the matrices we  have created in previous question

# Divide each element of matrix 'a' by 18
divided_a = [[element / 18 for element in row] for row in a]

# Divide each element of matrix 'b' by 18
divided_b = [[element / 18 for element in row] for row in b]

# Print matrix 'a' after division
print("Matrix 'a' after dividing each element by 18:")
for row in divided_a:
    print(row)

# Print matrix 'b' after division
print("Matrix 'b' after dividing each element by 18:")
for row in divided_b:
    print(row)

Matrix 'a' after dividing each element by 18:
[0.8888888888888888, 1.3888888888888888, 2.0, 2.7222222222222223, 3.5555555555555554]
[0.0, 0.05555555555555555, 0.2222222222222222, 0.5, 4.5]
[0.6666666666666666, 0.7777777777777778, 1.9444444444444444, 3.111111111111111, 3.5]
[0.3333333333333333, 0.6666666666666666, 1.0, 1.0, 1.3333333333333333]
[1.3888888888888888, 1.7777777777777777, 3.0555555555555554, 6.722222222222222, 13.555555555555555]
Matrix 'b' after dividing each element by 18:
[8.88888888888889, 13.88888888888889, 20.0, 27.22222222222222, 35.55555555555556]
[0.0, 0.05555555555555555, 2.2222222222222223, 5.0, 45.0]
[6.666666666666667, 7.777777777777778, 19.444444444444443, 31.11111111111111, 35.0]
[3.3333333333333335, 6.666666666666667, 10.0, 10.0, 13.333333333333334]
[13.88888888888889, 17.77777777777778, 30.555555555555557, 67.22222222222223, 135.55555555555554]


Question 11

In [ ]:



import numpy as np

# Assuming 'a' and 'b' are the matrices  we have created in pervious question
# Inverse of matrix 'a'
try:
    inverse_a = np.linalg.inv(a)
    print("Inverse of matrix 'a':")
    print(inverse_a)
except np.linalg.LinAlgError:
    print("Matrix 'a' is not invertible.")

# Inverse of matrix 'b'
try:
    inverse_b = np.linalg.inv(b)
    print("Inverse of matrix 'b':")
    print(inverse_b)
except np.linalg.LinAlgError:
    print("Matrix 'b' is not invertible.")

# Rank of matrix 'a'
rank_a = np.linalg.matrix_rank(a)
print("Rank of matrix 'a':", rank_a)

# Rank of matrix 'b'
rank_b = np.linalg.matrix_rank(b)
print("Rank of matrix 'b':", rank_b)

# Condition number of matrix 'a'
condition_number_a = np.linalg.cond(a)
print("Condition number of matrix 'a':", condition_number_a)

# Condition number of matrix 'b'
condition_number_b = np.linalg.cond(b)
print("Condition number of matrix 'b':", condition_number_b)

# Singular value decomposition (SVD) of matrix 'a'
U_a, S_a, Vt_a = np.linalg.svd(a)
print("Singular Value Decomposition of matrix 'a':")
print("U_a:", U_a)
print("S_a:", S_a)
print("Vt_a:", Vt_a)

# Singular value decomposition (SVD) of matrix 'b'
U_b, S_b, Vt_b = np.linalg.svd(b)
print("Singular Value Decomposition of matrix 'b':")
print("U_b:", U_b)
print("S_b:", S_b)
print("Vt_b:", Vt_b)

# Norm of matrix 'a'
norm_a = np.linalg.norm(a)
print("Norm of matrix 'a':", norm_a)

# Norm of matrix 'b'
norm_b = np.linalg.norm(b)
print("Norm of matrix 'b':", norm_b)

Inverse of matrix 'a':
[[ 6.05930290e-01  2.35924872e-01  1.08695652e-01 -9.50672152e-01
  -1.71807982e-01]
 [-2.03338751e-01 -1.49194095e-01 -1.52173913e-01  4.30863132e-01
   9.97731275e-02]
 [ 2.60734119e-02  7.99133144e-02  8.69565217e-02 -1.84037654e-02
  -5.40092103e-02]
 [-1.10490316e-01 -8.53988893e-02 -2.17391304e-02  1.28530069e-01
   5.03013680e-02]
 [ 1.34994808e-02  1.97300104e-02  1.84997357e-18 -1.86915888e-02
  -4.15368640e-03]]
Inverse of matrix 'b':
[[ 0.0567866   0.02079962  0.00802092 -0.0870016  -0.01531308]
 [-0.01792676 -0.01315326 -0.01341597  0.03798578  0.00879621]
 [ 0.00131801  0.00704532  0.00773075  0.00089164 -0.00476828]
 [-0.0096712  -0.00752894 -0.00114278  0.00993346  0.00435407]
 [ 0.00103162  0.00173944 -0.00023823 -0.00119464 -0.00025917]]
Rank of matrix 'a': 5
Rank of matrix 'b': 5
Condition number of matrix 'a': 412.1765222794268
Condition number of matrix 'b': 374.37423068088077
Singular Value Decomposition of matrix 'a':
U_a: [[-0.2797398   0.5

Question 12

In [ ]:
import numpy as np

# Create a column vector manually
column_vector = np.array([[1], [2], [3], [4], [5]])

# Calculate the norm of the column vector
norm = np.linalg.norm(column_vector)
print("Norm of the column vector:", norm)

# Create another column vector for inner product
inner_product_vector = np.array([[2], [4], [6], [8], [10]])

# Calculate the inner product of the two column vectors
inner_product = np.inner(column_vector.flatten(), inner_product_vector.flatten())
print("Inner product of the column vectors:", inner_product)

# Calculate the outer product of the two column vectors
outer_product = np.outer(column_vector, inner_product_vector.T)
print("Outer product of the column vectors:")
print(outer_product)

Norm of the column vector: 7.416198487095663
Inner product of the column vectors: 110
Outer product of the column vectors:
[[ 2  4  6  8 10]
 [ 4  8 12 16 20]
 [ 6 12 18 24 30]
 [ 8 16 24 32 40]
 [10 20 30 40 50]]


Question 13

In [ ]:
import math

def derivative(f, a, method='central', h=0.01):
    # Implementation of the numerical derivative using different methods.
    # Returns the approximate derivative of function f at point a.
    if method == 'forward':
        return (f(a + h) - f(a)) / h# using first derivative formula
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    elif method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    else:
        raise ValueError("Invalid method, supported methods are 'forward', 'backward', and 'central'.")

def ex(x):#an maths function for determining exponent
    return math.exp(x)

def cos(x):# an maths function for determining cosine
    return math.cos(x)


x = 0.5 # value of x is intialized

derivative_ex_forward = derivative(ex, x, method='forward')# for x =0.5 forward derivative is carried out in ex()
derivative_ex_backward = derivative(ex, x, method='backward')#for x =0.5 backward derivative is carried out in ex()
derivative_ex_central = derivative(ex, x, method='central')#for x =0.5 central derivative is carried out in ex()

derivative_cos_forward = derivative(cos, x, method='forward')#for x =0.5 forward derivative is carried out in cos()
derivative_cos_backward = derivative(cos, x, method='backward')#for x =0.5 backward derivative is carried out in cos()
derivative_cos_central = derivative(cos, x, method='central')#for x =0.5 backward derivative is carried out in cos()

print("Testing on ex(x) at x =",x)
print("Forward difference:", derivative_ex_forward)
print("Backward difference:", derivative_ex_backward)
print("Central difference:", derivative_ex_central)

print("\nTesting on cos(x) at x =",x)
print("Forward difference:", derivative_cos_forward)
print("Backward difference:", derivative_cos_backward)
print("Central difference:", derivative_cos_central)

Testing on ex(x) at x = 0.5
Forward difference: 1.6569924245758205
Backward difference: 1.6405050744749294
Central difference: 1.648748749525375

Testing on cos(x) at x = 0.5
Forward difference: -0.483805424462147
Backward difference: -0.4750296719748692
Central difference: -0.4794175482185081


Question 14


In [ ]:
import pandas as pd
# Dowloaded an aws_file from google and save it as .csv
df = pd.read_csv("/content/surface_data.csv", index_col=0)
# defined the path of the file
print(df)

               tempr        ap      ws       wd       rh
obstime                                                 
1985-02-26  -10.0000  983.0250  16.125   11.750   64.875
1985-02-27  -12.6250  981.5750   5.875   29.250   58.625
1985-02-28  -17.1875  983.7750   3.000   99.000   55.125
1985-03-01 -507.6250  986.3375  19.125 -493.625 -999.000
1985-03-02 -257.3125  497.7500  33.875 -243.000 -224.125
...              ...       ...     ...      ...      ...
2010-12-27   -0.1125  996.9375   5.625   15.750 -999.000
2010-12-28   -0.7000  994.6750  19.250    9.750 -999.000
2010-12-29    0.6375  994.2875  22.250   10.250 -999.000
2010-12-30    1.4375  992.5125  14.500   10.250 -999.000
2010-12-31    0.9500  989.2000  16.500   11.500 -999.000

[9385 rows x 5 columns]
